export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT = 'LOGOUT';
export const GET_USER_DATA = 'GET_USER_DATA';
export const UPDATE_MEAL_DATA = 'UPDATE_MEAL_DATA';
export const GET_NET_DATA = 'GET_NET_DATA';
export const GET_INDIVIDUAL_DATA = 'GET_INDIVIDUAL_DATA';